configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

repoServer:
  # Use init containers to configure custom tooling
  # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
  volumes:
  - name: custom-tools
    emptyDir: {}

  initContainers:
  - name: install-ksops
    image: viaductoss/ksops:v4.3.3
    command: [ "/bin/sh", "-c" ]
    args:
    - echo "Installing KSOPS..."; mv ksops /custom-tools/; mv kustomize /custom-tools/; echo "Done.";
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/kustomize
    name: custom-tools
    subPath: kustomize
  - mountPath: /usr/local/bin/ksops
    name: custom-tools
    subPath: ksops

  serviceAccount:
    create: true
    name: "argocd-repo-server"
    annotation:
      eks.amazonaws.com/role-arn: arn:aws:iam::026090549419:role/argocd-kms-role
    labels: {}
    automountServiceAccountToken: true

  env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-argocd-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-argocd-secret
        key: AWS_SECRET_ACCESS_KEY
server:
  service:
    type: LoadBalancer

# Enable Kustomize Alpha Plugins via Argo CD ConfigMap, required for ksops
