apiVersion: v1
kind: Secret
metadata:
    name: postgres
data:
    PG_URL: ENC[AES256_GCM,data:my7tz1wodNNYAePVxxsAJz5KePOW0Fe0YtlwWyz537xxOxmo04cL2h4dOxr4eG5UqpWgwWY43kvFolmhNyw7+UkShUJZXZEcqyZ+3A3/wDTe+9Fs3SICGb1O5/iYZ2xC6Idm8d44,iv:PmKlJYd1Uh4D/87pa8CXzfOwlZUyULdun5feoBYF3ek=,tag:/rwhjA0OTH3AECkxjyvGuw==,type:str]
    PG_DSN_URL: ENC[AES256_GCM,data:c+YQH0OBMu1chLD+N6RMcSTEkCstgR5mWCtmDPrd9mZve+IqrZ5ut0vzcgsZldDFfV6MqF/HApvqlpPt+Grx4kvCoNWBTHYJiDcc6Q8i7v3BteCHqUWJm2NLve/1PinC9fLnllY5J50acsiceuFd8PWobPjvuewzg50Nlyc5GKw=,iv:tu+4sxk+JgKBRzI8wvONeAHNvPnl3Xax1F+c/SzB5HM=,tag:qo0QNOHd8jk/y3L/TQPjYg==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:026090549419:key/93462361-1983-4556-bd08-7503d9060388
          created_at: "2025-05-15T06:33:39Z"
          enc: AQICAHgHS951vVpIgtTT1mwqnX4Mc9K9dtgy74EVVMqMsZWkAAFEglOuzkGwdTlwGdBQatTUAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM530RWsLMVzMmeJWmAgEQgDtjAptaCiWHB9tftqW9kyh22ixqn8zQBwNUs1tSv6ojDlGI4/N8j4NiZ/2PmWAeK5BNthiQ3HP08rS3UQ==
          aws_profile: ""
    lastmodified: "2025-05-15T06:33:40Z"
    mac: ENC[AES256_GCM,data:3f2pQI9PXa/4Uodfbw2I8A40O8vsiDcREH5ifJW8S1cEl3W4lX/GOjpH4AeQKESheTx3jdsTH9G8EVHGRffscGtZkGh/V/xKHrMxlaKbaRj1RLkQZMzF1W5mUdWw7K3i8FI1B68tUJpCOeeU8U8saZJT0+sjZF8um71pUmkW9vE=,iv:wohqdSAs9hK61VTxEVaPA0esY6oHqQP+zA493Ltzi4Y=,tag:eHQ1forQb/wvDlQ1OA3ODQ==,type:str]
    encrypted_regex: ^data$
    version: 3.10.2
