apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
data:
    RABBITMQ_URL: ENC[AES256_GCM,data:SPv7YYfC6+42aZKmPj8TTuwopB6hCCOpZBscQ4otf/Y6,iv:o1sqHsX9AC/YUWBo9PJlJccfW2KH6zgBQDYz4ESMfYE=,tag:jJA34pQxQk22PFYwi8KBeA==,type:str]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:Rc78M6k=,iv:6fdVoJOfJajFbrBuMxjJ2NsFxjUOGsXAxQxiHXtVZJQ=,tag:QVZPteIFE9OTNXSvy/VV3Q==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:qUaDpyc=,iv:fXF6ySJCV2BjQgrTRggsmA9Crhry0lbsvmGLscVTRX0=,tag:kwgzJdYafmJ3Xw6wMvJWnQ==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:026090549419:key/93462361-1983-4556-bd08-7503d9060388
          created_at: "2025-05-15T06:33:40Z"
          enc: AQICAHgHS951vVpIgtTT1mwqnX4Mc9K9dtgy74EVVMqMsZWkAAFWy3DJoacOdRQOaTh5g+0nAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbG7GYHufOvYO2hNmAgEQgDte3SSZqjn3xyAA0kqmiRsdVYOl7Y8e1wI+/L616DCK/JI/t42mJxuUwF66FpFW2F4CeH1RQRMZQRP79w==
          aws_profile: ""
    lastmodified: "2025-05-15T06:33:40Z"
    mac: ENC[AES256_GCM,data:6KTyAREPrJV50GBWBJlogdepqicNW8/VHzOwRVe5/czu135zJuWcYD0Pfi79yCtN/Bn5HAdVaJ5w4i1HeiOwvS8CgPt7aY1DYmU1Adrhg1/NNMUII+h67OuqGsQU6wkUe8/PP8i+NrqKzt9l3PBfIiq5GPwd3frFKiCreDPtBMk=,iv:SEPorQZcywXw91y1a8Phk7p36hX91ZDxLex+WDBY6KE=,tag:LorGe1+cXcCeTBrOwXJmHg==,type:str]
    encrypted_regex: ^data$
    version: 3.10.2
