apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    RABBITMQ_URL: ENC[AES256_GCM,data:QidtVmVHLNj2yu9Q1HABWeyg0D3h6ca8IunwDRTg6Pul,iv:cknN+nJtUJAvxi+uuKFXdUKCbHyfxUOfeWrG2C/UFtA=,tag:/sd/p5l2W8PVg7HM50XcRA==,type:str]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:ThO7XVw=,iv:jewMJ8Xnywt24u1i+HobMmKyIMuEVtVKdytsrHcgdTQ=,tag:XoJPCwHH1wJT/ITs9+Tf8Q==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:dIcs3FQ=,iv:7nNbgsOzGKZQQRmx8WlgAlhQ7sEJbKnuea44pAnL++Y=,tag:8Uh0ewRx+rJQC4tt7PkU7g==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:026090549419:key/93462361-1983-4556-bd08-7503d9060388
          created_at: "2025-05-16T16:49:25Z"
          enc: AQICAHgHS951vVpIgtTT1mwqnX4Mc9K9dtgy74EVVMqMsZWkAAE1dQgcUAjXOCjI0AVxetH/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOBv3dhHExuCYnKPUAgEQgDvSkMWu9lGumbZUMIfn1KQ/AlpMG0NjEO8GlBTD3BIyjjHM4h8JUr1D2Oq8hTP07RNnIqxMvHQcKGotTQ==
          aws_profile: ""
    lastmodified: "2025-05-16T16:49:26Z"
    mac: ENC[AES256_GCM,data:cLDu8PB2N4WBqRY4hBOpGZHHAz8RPWnHv/zPUq6dlas5LFGifkKqMD4KGhRoia7vbps9dzz97H7RyaavI7gAldqWlQO+bmLwANVbW4P8DUFt1W5OzYK860HmXJeG8KgEvjiFPSDT75x3zTnTOcUzqG00AeZfyLzaxp7sKEMM2yw=,iv:kFJacnASuMmAdKmoIQSNLwY1YENC3JpuvVyGpqaGcYo=,tag:JLHnVOP1Q5lYzWxiCNg9UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
