apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
data:
    RABBITMQ_URL: ENC[AES256_GCM,data:UFUV/mUzQatueBZmZ9eTYUy5fWv4jGVHe9V3jQXXPSeg,iv:c7iy55yPpczXfklQJ5mbVncvheFrn8hYAInuCZsfajo=,tag:SVQbAa7VE33iBJSIA+bVmw==,type:str]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:eY4zdkc=,iv:9IyvQlqdcyc/c8Kz5Bk55eMnfU95NkVy4vizBHThCHE=,tag:XWLZu992hKU7KGIFx3nJXA==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:VBwurfM=,iv:6njPc8O4jwpIX6ESf5W8QVnlliW0ps3OcITEcLwhWXE=,tag:Gu985Y0jUWWn88BdyETaRw==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:026090549419:key/93462361-1983-4556-bd08-7503d9060388
          created_at: "2025-05-16T16:16:39Z"
          enc: AQICAHgHS951vVpIgtTT1mwqnX4Mc9K9dtgy74EVVMqMsZWkAAFT22dOpJCaJOtHSVPsBVAbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK343kWinE6UnNsjJAgEQgDucxBylPzRuNeLcbK7L10PviaoNwhARdV0XXIxwkTZ6pASosaYlNh2Y6YcYeRRTUEfFjpd8T0/l7YpdNw==
          aws_profile: ""
    lastmodified: "2025-05-16T16:16:40Z"
    mac: ENC[AES256_GCM,data:FTE0jWZuUsofuVCeSyOJ6+47g34z3MhrMTIOUcuvVhC6qwDWsAWnj44WRbxbkKv7/1hiJnwN8wsaRUaLL+DyVOx5tGhgJFU/LS6yhTeIxyjf+q5Tpn21oxWYz4/YG2sbKAT1Dk1UgtpY4oScf5T7ubTok2AcsHhuq+yypx+1gLE=,iv:DfhM9HRk4x7D5KE6evasK6AyIjc4UHrLkyyPeZ35RkA=,tag:2gBltLGEPvBoWSsMRIlh9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
