apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enc-secret-test
  namespace: argocd # Argo CD must be installed in this namespace
spec:
  project: opswat-training-final
  source:
    repoURL: https://github.com/ntthuan0106/opswat-training-final.git
    targetRevision: main # or whatever branch you are using
    path: argo-cd/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffeeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
