name: Manual Terraform Destroy (Dev)

on:
  workflow_dispatch:  # Chỉ chạy khi được gọi thủ công từ giao diện GitHub

jobs:
  dev-terraform-destroy:
    name: Terraform Destroy (Dev)
    runs-on: ubuntu-latest
    environment: dev-env

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform/workspaces/dev
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./terraform/workspaces/dev
        run: terraform destroy -var-file=values.tfvars -auto-approve
        env:
          TF_VAR_DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
