name: Dev Deploy

on:
  push:
      branches:
      - main
      paths:
        - '.github/workflows/dev-deploy.yml'
        - './terraform/workspaces/dev/**'
  workflow_run:
      workflows: ["Trivy Scan from image-list.yml"]
      types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/workspaces/dev
    environment: dev-env
    env: 
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform/workspaces/dev
        env:
          # Nếu bạn dùng secret cho cloud provider (AWS, GCP, v.v.)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/workspaces/dev
        env:
          TF_VAR_DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}