name: Trivy Scan from image-list.yml

on:
  push:
    branches:
    - main
    paths: 
      - 'trivy/**'
      - 'scripts/scan-images.sh'
      - 'scripts/tag-images.sh'
      - 'scripts/push-images.sh'
      - '.github/workflows/trivy-scan-docker-image.yaml'
  pull_request:


permissions:
  id-token: write
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    environment: trivy scan
    env:
      S3_BUCKET: thuan-opswat-test
      S3_PREFIX: trivy
      IMAGE_LIST_FILE: trivy/scan-image-list.yml
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_HUB_PRIVATE_REPOSITORY_NAME: ${{ vars.DOCKER_HUB_PRIVATE_REPOSITORY_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install yq (YAML parser)
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
    
    - name: Set executable permission for scripts
      run: chmod +x scripts/*.sh

    - name: Scan image
      run: ./scripts/scan-images.sh
    - name: Tag images
      run: ./scripts/tag-images.sh "${{ env.DOCKER_USERNAME }}" "${{ env.DOCKER_HUB_PRIVATE_REPOSITORY_NAME }}"

    - name: Docker login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Push tagged images to private docker hub repo
      run: ./scripts/push-image.sh \
        "${{ env.DOCKER_USERNAME }}" \
        "${{ env.DOCKER_HUB_PRIVATE_REPOSITORY_NAME }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MINH }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MINH }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Upload Trivy reports to S3
      run: |
        aws s3 cp trivy/report/ s3://$S3_BUCKET/$S3_PREFIX/ --recursive --acl bucket-owner-full-control